version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5050:80'
      - '5051:443'

volumes:
  postgres:
    driver: local
